[package]
name = "aws-cost-notification"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.1.7", features = ["behavior-version-latest"] }
aws-sdk-costexplorer = "1.33.0"
tokio = { version = "1", features = ["full"] }